### ISSUE TITLE
Windows 11 installation failure

### ISSUE THREAD

**Issue by codebytere** [nornagon/electron-minidump#17]
`electron-minidump` currently fails to install on Windows 11. 

Current device specs:

```
Device name	CODEBYTERE-WIN-WORK
Processor	Apple Silicon   3.20 GHz  (4 processors)
Installed RAM	8.00 GB
Device ID	451128FD-A1D4-4A11-8625-28CF5A57A1F6
Product ID	00330-81048-67632-AA988
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen and touch support with 2 touch points
```

<details><summary>Stacktrace</summary>
<p>

```
codebytere@CODEBYTERE-WIN-WORK MINGW64 ~/Developer/electron-gn/src/electron (main)
$ npm install -g electron-minidump
npm ERR! code 1
npm ERR! path C:\Users\codebytere\AppData\Roaming\npm\node_modules\electron-minidump\node_modules\minidump
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build.js
npm ERR! C:\Users\codebytere\AppData\Roaming\npm\node_modules\electron-minidump\node_modules\minidump\build.js:24   
npm ERR!   if (result.error) throw result.error
npm ERR!                     ^
npm ERR!
npm ERR! Error: spawnSync C:\Users\codebytere\AppData\Roaming\npm\node_modules\electron-minidump\node_modules\minidump\deps\breakpad\configure ENOENT
npm ERR!     at Object.spawnSync (node:internal/child_process:1112:20)
npm ERR!     at Object.spawnSync (node:child_process:827:24)
npm ERR!     at spawnSync (C:\Users\codebytere\AppData\Roaming\npm\node_modules\electron-minidump\node_modules\minidump\build.js:23:31)
npm ERR!     at Object.<anonymous> (C:\Users\codebytere\AppData\Roaming\npm\node_modules\electron-minidump\node_modules\minidump\build.js:42:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawnSync C:\\Users\\codebytere\\AppData\\Roaming\\npm\\node_modules\\electron-minidump\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   path: 'C:\\Users\\codebytere\\AppData\\Roaming\\npm\\node_modules\\electron-minidump\\node_modules\\minidump\\deps\\breakpad\\configure',
npm ERR!   spawnargs: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\codebytere\AppData\Local\npm-cache\_logs\2023-06-16T10_41_42_093Z-debug-0.log
```

</p>
</details>

**Comment by samuelmaddock** [comment]
Same results on Windows 10

```
Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Device ID	C00D9FC1-7D37-46EC-A7CD-92A0D8930D77
Product ID	00329-00000-00003-AA229
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points
```

Same issues reported in https://github.com/electron/node-minidump/issues/51 and https://github.com/electron/node-minidump/issues/62
